TWI-44 Create env file
pm888/Twitter pull request #34
Opened 2023-07-06 16:55 UTC by pm888

2023-07-07 11:53 UTC, bunin requested changes

2023-07-07 11:53 UTC, bunin commented on cmd/app/main.go
> +		err := admin.LoadEnvFile()
where is this code?

2023-07-07 12:19 UTC, pm888 commented on cmd/app/main.go
> +		err := admin.LoadEnvFile()
done

2023-07-07 13:09 UTC, bunin requested changes

2023-07-07 13:09 UTC, bunin commented on internal/database/pg/pg.go
>  	db, err := sql.Open("postgres", connStr)
you are still connecting using hardcoded values

2023-07-07 13:09 UTC, bunin commented on .env
> +DB_PG_PASSWORD=postgrespw
you should not push secrets

2023-07-07 13:10 UTC, bunin commented on cmd/app/main.go
> +	wg.Wait()
this waitgroup makes no sense

2023-07-07 13:11 UTC, bunin requested changes

2023-07-07 13:11 UTC, bunin commented on internal/server/server.go
> +	fmt.Println(fmt.Sprintf("Server was run %s:%s", admin.ServerHost, admin.ServerPort))
you've changed the log output but not the actual listen address

2023-07-07 13:52 UTC, bunin commented on internal/server/server.go
> +	fmt.Println(fmt.Sprintf("Server was run %s:%s", admin.ServerHost, admin.ServerPort))
there's fmt.Printf

2023-07-11 15:00 UTC, bunin requested changes
https://github.com/mo-pm888/twitter/pull/34/files#r1255801443

2023-08-12 06:15 UTC, bunin approved these changes

2023-08-12 06:19 UTC, merged